import { describe, expect, it } from 'vitest';
import corpus from './fixtures/open-gambit/real-corpus-2026-09-11.json';
import prodCandidates from './fixtures/open-gambit/prod-candidates-2026-09-11.json';
import { strategicSubstance } from '../src/open-gambit/eligibility';
import { qualificationGate } from '../src/open-gambit/policy';
import { isVersionNoiseItem } from '../src/open-gambit/sources';
import type { GambitEvidence, GambitSourceTier } from '../src/open-gambit/types';

/**
 * Open Gambit — Phase 0 real-corpus regression baseline (task B6).
 *
 * This file freezes the CURRENT zero-pass state of the discovery gate against
 * REAL allowlisted-source corpus, not synthetic sentences. Companion fixture:
 * `tests/fixtures/open-gambit/real-corpus-2026-09-11.json` (generated by
 * `scripts/build-open-gambit-corpus.mts`) and the sanitized production funnel
 * `tests/fixtures/open-gambit/prod-candidates-2026-09-11.json`.
 *
 * ZERO PUBLICATION IS A HEALTHY RESULT. The `0 passed` assertions below are
 * NOT a target and must never be "fixed" by weakening behaviour. They exist so
 * that any change to admission has to be an explicit, reviewed decision.
 *
 * STAGE 1 UPDATE PROTOCOL (when `eligibility.ts` is deliberately relaxed):
 *   1. Re-run `npx vite-node scripts/build-open-gambit-corpus.mts` to produce a
 *      NEW dated fixture. Do NOT edit the 2026-09-11 fixture rows.
 *   2. Add the new fixture as a separate case with its own expected numbers.
 *   3. Keep this file's `2026-09-11` case asserting the historical baseline by
 *      replaying the frozen quotes through the NEW rules, and state in the PR
 *      which rows flipped and why.
 *   4. Never delete a frozen row to make a suite green.
 */

interface CorpusEntry {
  sourceId: string;
  sourceType: string;
  stableId: string;
  title: string;
  url: string;
  publishedAt: string | null;
  quote: string;
  quoteLength: number;
  summary: string;
  sourceTier: GambitSourceTier;
  qualified: boolean;
  reason: string | null;
  detail: string;
  score: number;
  signalTypes: string[];
}

const entries = corpus.entries as unknown as CorpusEntry[];

function evidenceFor(entry: CorpusEntry): GambitEvidence {
  return {
    sourceId: entry.sourceId,
    title: entry.title,
    publisher: entry.sourceId,
    publishedAt: entry.publishedAt,
    snapshotId: 0,
    sourceTier: entry.sourceTier,
    canonicalUrl: entry.url,
    quote: entry.quote,
    role: 'FACT',
    contentHash: 'a'.repeat(64),
  };
}

describe('Open Gambit real-corpus baseline (2026-09-11, 30-day window)', () => {
  it('fixture covers every enabled allowlisted source', () => {
    expect(corpus.sourceCount).toBe(14);
    expect(corpus.registryErrors).toEqual([]);
    expect(corpus.productionMaxSourceBytes).toBe(128_000);
    // Frozen observation: at fixture time every source was reachable under the
    // live production byte cap. This does NOT hold on days when a large
    // rendered release-note pushes a GitHub atom feed past the cap.
    expect(corpus.productionPass.fetchCount).toBe(14);
    expect(corpus.productionPass.sourcesSucceeded).toBe(14);
  });

  // ---------------------------------------------------------------------
  // The assertions below are HISTORICAL FACTS ABOUT THIS FIXTURE FILE, not
  // current behaviour. The 2026-09-11 rows are frozen evidence and were never
  // edited. What the CURRENT rules do to those same frozen quotes is asserted
  // separately, immediately after, per this file's STAGE 1 UPDATE PROTOCOL.
  // ---------------------------------------------------------------------

  it('records the historical zero-pass state of 2026-09-11: 0 of 98 real entries qualified', () => {
    expect(entries).toHaveLength(98);
    expect(entries.filter(entry => entry.qualified === true)).toHaveLength(0);
  });

  it('records the historical signal-hit count of 2026-09-11: 0 of 98 hit any strategic signal', () => {
    expect(entries.filter(entry => entry.signalTypes.length > 0)).toHaveLength(0);
  });

  it('records the historical rejection distribution of 2026-09-11', () => {
    const byDetail = new Map<string, number>();
    for (const entry of entries) byDetail.set(entry.detail, (byDetail.get(entry.detail) ?? 0) + 1);
    expect(Object.fromEntries(byDetail)).toEqual({ ROUTINE_MAINTENANCE: 45, INSUFFICIENT_STRATEGIC_SUBSTANCE: 53 });

    const byReason = new Map<string, number>();
    for (const entry of entries) byReason.set(String(entry.reason), (byReason.get(String(entry.reason)) ?? 0) + 1);
    expect(Object.fromEntries(byReason)).toEqual({ LOW_STRATEGIC_VALUE: 96, INSUFFICIENT_EVIDENCE: 2 });
  });

  // ---------------------------------------------------------------------
  // STAGE 1 (Phase 1) UPDATE: the frozen quotes are replayed through the NEW
  // rules. Exactly these four rows flip, and every other row keeps its
  // historical rejection.
  // ---------------------------------------------------------------------

  it('replays the frozen quotes through the Phase 1 rules and flips exactly four rows', () => {
    const admitted = entries
      .filter(entry => qualificationGate({
        headline: entry.title,
        summary: entry.summary,
        content: entry.summary,
        evidence: [evidenceFor(entry)],
      }).qualified)
      .map(entry => entry.title)
      .sort();

    expect(admitted).toEqual([
      'AI Scan for pull request APIs in public preview',
      'Enterprise managed permissions for GitHub Copilot agent operations',
      'GitHub Advanced Security expands trial availability',
      'MAI-Code-1-Flash deprecated',
    ]);
    // 4 of 98, not 0: the twenty Phase 0 signals matched nothing at clause
    // granularity, so the previous state was a matching defect, not a corpus
    // with nothing in it. 94 rows still reject, which is the point.
    expect(admitted).toHaveLength(4);
  });

  it('still rejects the Phase 0 named negative targets under the Phase 1 rules', () => {
    // These four were the audit's calibration set. The first must flip; the
    // other three must NOT, or the new signals are admitting routine work.
    const byTitle = new Map(entries.map(entry => [entry.title, entry]));
    const decisionFor = (title: string) => {
      const entry = byTitle.get(title);
      expect(entry, `fixture must still contain ${title}`).toBeDefined();
      return qualificationGate({
        headline: entry!.title,
        summary: entry!.summary,
        content: entry!.summary,
        evidence: [evidenceFor(entry!)],
      });
    };

    expect(decisionFor('AI Scan for pull request APIs in public preview').qualified).toBe(true);
    expect(decisionFor('Refreshed repository pull requests page in public preview').qualified).toBe(false);
    expect(decisionFor('CodeQL 2.27.0 adds support for Linux ARM64').qualified).toBe(false);
    expect(decisionFor('[v1.31.0] Custom labels for Sandboxes, More resilient downloads and more').qualified).toBe(false);
  });

  it('confines the Phase 1 signal hits to the source that publishes real announcements', () => {
    // Before Phase 1 NO source contributed a signal hit. Now exactly one does:
    // github-changelog, the only source in this registry whose feed body is
    // first-party announcement prose. The RSS sources publish 50-140 character
    // marketing blurbs, which cannot carry an event plus its object, and the
    // GitHub release feeds publish versioned changelogs. Widening recall past
    // this point is a SOURCE STRUCTURE problem (stage 2), not a signal problem.
    const hitting = [...new Set(entries
      .filter(entry => strategicSubstance([evidenceFor(entry)]).signalTypes.length > 0)
      .map(entry => entry.sourceId))];
    expect(hitting).toEqual(['github-changelog']);
  });
});

describe('Open Gambit production candidate funnel baseline (2026-09-11)', () => {
  const candidates = prodCandidates.candidates;

  it('freezes the production funnel totals', () => {
    expect(candidates).toHaveLength(58);
    expect(prodCandidates.counts.total).toBe(58);
  });

  it('freezes 0 QUALIFIED candidates in production', () => {
    expect(candidates.filter(candidate => candidate.status === 'QUALIFIED')).toHaveLength(0);
    expect(candidates.every(candidate => candidate.status === 'REJECTED')).toBe(true);
  });

  it('freezes 51 REJECTED + LOW_STRATEGIC_VALUE candidates', () => {
    expect(candidates.filter(candidate => candidate.status === 'REJECTED'
      && candidate.rejectionReason === 'LOW_STRATEGIC_VALUE')).toHaveLength(51);
    expect(prodCandidates.counts.byRejectionReason.LOW_STRATEGIC_VALUE).toBe(51);
  });

  it('freezes the remaining rejection taxonomy', () => {
    expect(prodCandidates.counts.byRejectionReason).toEqual({
      INSUFFICIENT_EVIDENCE: 2,
      LOW_STRATEGIC_VALUE: 51,
      NON_FALSIFIABLE: 4,
      POLITICAL_TOPIC_EXCLUDED: 1,
    });
  });

  it('replays the Phase 1 version-noise pre-filter over the production titles', () => {
    // The sanitized fixture has no bodies, so the version-ONLY rule resolves in
    // its strictest form (short body). Fifteen production candidates carry an
    // unconditional pre-release marker and can never be a publication candidate
    // again; the twenty-seven version-only titles depend on a body length this
    // fixture deliberately does not contain.
    const prerelease = candidates.filter(candidate => /(?:nightly|canary|[\-._](?:rc|alpha|beta|dev|stage)\d*(?:[\s.\-]|$))/iu.test(candidate.headline));
    expect(prerelease).toHaveLength(15);
    expect(candidates.filter(candidate => isVersionNoiseItem(candidate.headline, '')).length).toBeGreaterThanOrEqual(prerelease.length);
    // No title-based filter can admit anything on its own: admission still needs
    // evidence-quote signals, which this fixture does not carry.
    expect(candidates.every(candidate => candidate.status === 'REJECTED')).toBe(true);
  });

  it('is sanitized: no summary, fingerprint, quote or raw body leaked into the fixture', () => {
    for (const candidate of candidates) {
      expect(Object.keys(candidate).sort()).toEqual([
        'discoveredAt', 'evidenceSufficient', 'headline', 'id',
        'rejectionReason', 'sourceIds', 'status', 'strategicValue',
      ]);
    }
  });
});
